version: '3.8'
services:
  nats:
    image: nats:2.10
    ports:
      - "4222:4222"
      - "8222:8222"

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    volumes:
      - ./scheduler:/app
    depends_on:
      - nats
    environment:
      NATS_URL: "nats://nats:4222"
      TASKS_SUBJECT: "tasks"

  executor:
    build:
      context: .
      dockerfile: executor/Dockerfile
    volumes:
      - ./executor:/app
    depends_on:
      - nats
    environment:
      NATS_URL: "nats://nats:4222"
      TASKS_SUBJECT: "tasks"
      TASKS_QUEUE_GROUP: "executors"

  # api:
  #   build:
  #     context: .
  #     dockerfile: api/Dockerfile
  #   volumes:
  #     - ./api:/app
  #   ports:
  #     - "8080:8080"
