version: '3.8'
services:
  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    volumes:
      - ./scheduler:/app
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: "amqp://user:password@rabbitmq:5672/"

  # executor:
  #   build:
  #     context: .
  #     dockerfile: executor/Dockerfile
  #   volumes:
  #     - ./executor:/app
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     RABBITMQ_URL: "amqp://user:password@rabbitmq:5672/"

  # api:
  #   build:
  #     context: .
  #     dockerfile: api/Dockerfile
  #   volumes:
  #     - ./api:/app
  #   ports:
  #     - "8080:8080"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
      - "rabbitmq_log:/var/log/rabbitmq"

volumes:
  rabbitmq_data:
  rabbitmq_log:
